# Generated by Django 6.0.6 on 2026-07-06 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('price', models.PositiveIntegerField(verbose_name='Цена ($)')),
                ('mileage', models.PositiveIntegerField(verbose_name='Пробег (км)')),
                ('fuel_type', models.CharField(choices=[('Бензин', 'Бензин'), ('Дизель', 'Дизель'), ('Газ/Бензин', 'Газ/Бензин'), ('Гибрид', 'Гибрид'), ('Электро', 'Электро')], default='Бензин', max_length=30, verbose_name='Топливо')),
                ('drive_type', models.CharField(choices=[('Передний привод', 'Передний привод'), ('Задний привод', 'Задний привод'), ('Полный привод', 'Полный привод')], default='Передний привод', max_length=30, verbose_name='Привод')),
                ('city', models.CharField(max_length=80, verbose_name='Город')),
                ('vin_code', models.CharField(blank=True, max_length=40, verbose_name='VIN / код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='AUTOUA', max_length=100)),
                ('phone', models.CharField(default='+380000000000', max_length=30)),
                ('telegram', models.CharField(default='@username', help_text='Telegram username, with or without @', max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.carlisting')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
